<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist>
<plist version="1.0">
<dict>
	<key>patterns</key>
	<array>

		<dict>
			<key>match</key>			
			<string>(?i)IX\/Y(\+D\))?|\+D\)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>

		<!--Comments-->
		<dict>
			<key>match</key>
			<string>;.*</string> <!--";" is the character to match, "." indicates any char (except newline), 
										"*" means 0 or more times, "$" means to end of line (not needed but whatever)-->
			<key>name</key>
			<string>comment.line.z80</string>
		</dict>

		<!--Directives-->
		<dict>
			<key>match</key>
			<string>#\w+</string> <!--"#" is char to match "*" mean 0+ times-->
			<key>name</key>
			<string>keyword.control.directive.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?i)(\b|\.)(org|ds|db|dw|dl|assume|list|nolist|end|equ)\b</string>
			<key>name</key>
			<string>keyword.control.directive.z80</string>
		</dict>

		<!--Labels-->
		<dict>
			<key>match</key>
			<string>^[\w\.]+:{1,2}(?=\s*;|\s*$)</string> <!--If it ends in ": " it's a label-->
			<key>name</key>
			<string> entity.name.function.label.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>^[A-Za-z\.]+[\w\.]*(?=\s*;|\s*$)</string>
			<key>name</key>
			<string> entity.name.label.z80</string>
		</dict>

		<!--Conditionals (NZ, Z etc.)-->
		<dict>
			<key>match</key>
			<string>(?i)\s(Z|NZ|C|NC|P|M|PO|PE)\b</string>
			<key>name</key>
			<string>keyword.conditionals.z80</string>
		</dict>
		
		<!-- Strings -->
		<dict>
			<key>match</key>
			<string>\".+\"</string>
			<key>name</key>
			<string>string.quoted.double.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\'.+\'</string>
			<key>name</key>
			<string>string.quoted.single.z80</string>
		</dict>

		<dict>
			<key>match</key>			
			<string>(?i)\s(ADC|ADD|AND|BIT|CALL|CCF|CP|CPD|CPDR|CPI|CPIR|CPL|DAA|DEC|DI|DJNZ|EI|EX|EXX|HALT|IM|IN|INC|IND|INDR|INI|INIR|JP|JR|LD|LDD|LDDR|LDI|LDIR|NEG|NOP|OR|OTDR|OTIR|OUT|OUTD|OUTI|POP|PUSH|RES|RET|RETI|RETN|RL|RLA|RLC|RLCA|RLD|RR|RRA|RRC|RRCA|RRD|RST|SBC|SCF|SET|SLA|SRA|SRL|SUB|XOR)\b</string>
			<key>name</key>
			<string>keyword.control.opcodes.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(?i)\s(b_call)</string>
			<key>name</key>
			<string>keyword.control.bcall.z80</string>
		</dict>

		<!--Numbers-->
		<dict>
			<key>match</key>
			<string>(\b|^)[0-9]+d?\b</string> <!--"+" means 1 or more-->
			<key>name</key>
			<string>constant.numeric.dec.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(\$|0x)\h+\b</string> <!--starts with "$", 0x is optional, \h means hex digits-->
			<key>name</key>
			<string>constant.numeric.hex.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\h+h\b</string> <!--\h means hex digits-->
			<key>name</key>
			<string>constant.numeric.hex.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\%[01]+\b</string> <!--starts with "%", only has 0 or 1 after-->
			<key>name</key>
			<string>constant.numeric.bin.z80</string>
		</dict>

		<dict>
			<key>match</key>
			<string>[01]+b\b</string> 
			<key>name</key>
			<string>constant.numeric.bin.z80</string>
		</dict>

		<!--Registers-->
		<dict>
			<key>match</key>
			<string>(?i)\b(A|B|C|D|E|F|H|L|I|R|IX|IY|IXH|IXL|IYH|IYL|AF|BC|DE|HL|PC|SP|AF')\b</string>
			<key>name</key>
			<string>keyword.registers.z80</string>
		</dict>	

		<dict>
			<key>match</key>			
			<string>(?i)(\w+(?=\s+?(?:EQU)\s+))</string>
			<key>name</key>
			<string>variable.equate.z80</string>
		</dict>

		<!--Catch-all for any other word, remove this if you don't use semantic tokens-->
		<dict>
			<key>name</key>
			<string>text.z80</string>
			<key>match</key>
			<string>\b\w+\b</string>
		</dict>
		

		<!--Operators-->
		<dict>
			<key>match</key>			
			<string>[%\/*\-+]</string>
			<key>name</key>
			<string>keyword.operator.z80</string>
		</dict>

	</array>
	<key>scopeName</key>
	<string>source.z80</string>
</dict>
</plist>
